name: ci

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: knowledge_exchange
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H 20.251.9.203 > ~/.ssh/known_hosts

      - name: Upload
        run: |
          ssh mateusz@20.251.9.203 "pkill java;true"
          ssh mateusz@20.251.9.203 "rm -rf /home/mateusz/backend"
          ssh mateusz@20.251.9.203 "git clone https://github.com/elektroniczna-gielda-wiedzy/backend.git"
          ssh mateusz@20.251.9.203 "cd backend; ./gradlew bootjar"
          ssh mateusz@20.251.9.203 "cd backend; ./gradlew --stop"
          ssh -n -f mateusz@20.251.9.203 "cd backend; nohup java -XX:+UseSerialGC -Xss512k -XX:MaxRAM=150m -jar build/libs/knowledge-exchange-project-1.0-SNAPSHOT.jar &"

  test_after_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: |
          git clone https://github.com/elektroniczna-gielda-wiedzy/backend-tests.git
          cd backend-tests
          python3 -m pip install -r requirements.txt
          sleep 10
          pytest -v --url=http://20.251.9.203
