name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H 20.251.9.203 > ~/.ssh/known_hosts

      - name: Upload
        run: |
          ssh mateusz@20.251.9.203 "pkill java;true"
          ssh mateusz@20.251.9.203 "rm -rf /home/mateusz/backend"
          ssh mateusz@20.251.9.203 "git clone https://github.com/elektroniczna-gielda-wiedzy/backend.git"
          ssh mateusz@20.251.9.203 "cd backend; ./gradlew bootjar"
          ssh mateusz@20.251.9.203 "cd backend; ./gradlew --stop"
          ssh -n -f mateusz@20.251.9.203 "cd backend; nohup java -XX:+UseSerialGC -Xss512k -XX:MaxRAM=150m -jar build/libs/knowledge-exchange-project-1.0-SNAPSHOT.jar &"
